---
title: "warmup_lab6"
output: html_document
date: "2024-01-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## 1) load libraries and bison 
```{r}
library(tidyverse)
bison <- read_csv("lab6/data/bison.csv")
bison
```
## clean names
```{r}
library(janitor)
bison <- clean_names(bison)
```

## 2) dimentions and structure
```{r}
#glimpse(bison) is prefered to run before running other codes, not neseccary though
```


```{r}
dim(bison)
```

```{r}
str(bison)
```
## 3) restrict variables sex, code, weight and yob
```{r}
bison_new <- select(bison, "data_code" , "animal_sex" , "animal_weight" , "animal_yob")
#bison_new <- bison %>% (PREFERED USE)
  #select(animal_code, animal_sex, animal_weight, animal_yob)
```

## 4) animals born between 1980 and 1990
```{r}
filter(bison_sel, animal_yob %in% c(1980:1990))
#bison_new %>% 
  #filter(animal_yob>=1980 & animal_yob<=1990)
```


## 5) how many F v M bison are represented b/w 1980 and 1990 
```{r}
males <- bison_new %>% 
  filter(animal_yob %in% c(1980:1990) & animal_sex=="M") 
#males <- bison_new %>% 
  #filter(animal_yob>=1980 & animal_yob<=1990) %>% 
  #filter(animal_sex=="M")
#males
table(males$animal_sex)
```


```{r}
females <- bison_new %>% 
  filter(animal_yob %in% c(1980:1990) & animal_sex=="F")
table(females$animal_sex)
```



## 6) which are larger on average b/w M and F b/w 1980 and 1990
```{r}
bison_new %>% 
  filter(animal_yob %in% c(1980:1990)) %>% 
  filter(animal_sex=="F") %>% 
  arrange(desc(animal_weight))
mean(females$animal_weight)
```

```{r}
bison_new %>% 
  filter(animal_yob %in% c(1980:1990)) %>% 
  filter(animal_sex=="M") %>% 
  arrange(desc(animal_weight))
mean(males$animal_weight)
```

